run:
  deadline: 1m
  tests: false
  exclude-files:
    - "testing.go"
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"

linters-settings:
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  depguard:
    rules:
      main:
        list-mode: lax
        allow:
          - $gostd
          - "github.com/peterbourgon/ff/v3/ffcli"

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
